version: '3.8'

services:
  sistema-indicacoes:
    build: .
    container_name: sistema-indicacoes
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sistema-indicacoes.rule=Host(`seudominio.com`)"
      - "traefik.http.routers.sistema-indicacoes.entrypoints=websecure"
      - "traefik.http.routers.sistema-indicacoes.tls.certresolver=letsencrypt"
      - "traefik.http.services.sistema-indicacoes.loadbalancer.server.port=80"

networks:
  web:
    external: true